language: java

# masn. add docker related.
# ref: https://docs.travis-ci.com/user/docker/
services:
  - docker

before_install:
  - docker build -t helloworld .
  - docker run -d -p 127.0.0.1:8080:8080 helloworld
#  carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
#  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
# masn. end docker

# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
# install:
# - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# script:
# - mvn test
# 4 lines commented out. working.
# modified install and script per https://blog.frankel.ch/travis-ci-tutorial-for-java-projects/
install: true
script: mvn clean install
